<Project Sdk="Microsoft.NET.Sdk">
  <Sdk Name="Bluehill.MSBuild.Sdk" />
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <NoWarn>$(NoWarn);CA1819</NoWarn>
    <RootNamespace>Dotup</RootNamespace>
    <Platforms>x64</Platforms>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <OptimizationPreference>Size</OptimizationPreference>
    <EventSourceSupport>false</EventSourceSupport>
    <MetricsSupport>false</MetricsSupport>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
    <Http3Support>false</Http3Support>
    <IlcGenerateMapFile>true</IlcGenerateMapFile>
    <AssemblyDescription>A .NET version manager</AssemblyDescription>
    <AssemblyVersion>0</AssemblyVersion>
    <FileVersion>0.0.0</FileVersion>
    <Version>0.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="ConsoleAppFramework" />
    <Using Include="Semver" />
    <Using Include="Spectre.Console" />
    <Using Include="System.Diagnostics.CodeAnalysis" />
    <Using Include="System.Text.Json" />
    <Using Include="System.Text.Json.Serialization" />
    <Using Include="Dotup.Constants" Static="true" />
    <Using Include="Dotup.Functions" Static="true" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Bluehill.Features" />
    <PackageReference Include="ConsoleAppFramework">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Semver" />
    <PackageReference Include="Spectre.Console" />
    <PackageReference Include="Spectre.Console.Analyzer">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
