includes("../include.lua")
add_rules("mode.debug", "mode.release")
set_defaultmode("debug")
set_plat("windows")
set_arch("x86")
set_toolchains("clang-cl[llvm]")
set_languages("c17", "cxx23")
set_config("nomtd", true)

set_runtimes("MT")
set_policy("build.optimization.lto", is_mode("release"))
add_requires("minhook", {plat = "windows", arch = "x86", configs = {cxflags = {"-m32", "-msse3", "--target=i686-pc-windows-msvc"}}})

target("xinput1_3")
    add_rules("edgemod")
    add_defines("BLUEHILLLOADER_EXPORTS")
    add_files("src/*.cpp", "src/*.cppm", "src/Resource.rc")
    add_shflags("-def:src/BluehillLoader.def", {force = true})
    add_headerfiles("src/BluehillLoader.h")
    add_packages("minhook")
