name: test3

on:
  workflow_run:
    workflows:
      - test1
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.pull_requests.url != null && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run test
        run: |
          echo "$VALUE1"
        env:
          VALUE1: ${{ github.event.workflow_run.pull_requests.url }}
