name: test2

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run sleep
        run: sleep 10s
      - name: Run test
        run: echo "test2"
